# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'payment_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(825, 566)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btnCalculateSalary = QtWidgets.QPushButton(self.centralwidget)
        self.btnCalculateSalary.setGeometry(QtCore.QRect(340, 300, 98, 24))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btnCalculateSalary.setFont(font)
        self.btnCalculateSalary.setObjectName("btnCalculateSalary")
        self.linePayment = QtWidgets.QLineEdit(self.centralwidget)
        self.linePayment.setGeometry(QtCore.QRect(390, 264, 127, 20))
        self.linePayment.setText("")
        self.linePayment.setReadOnly(True)
        self.linePayment.setObjectName("linePayment")
        self.labelPayment = QtWidgets.QLabel(self.centralwidget)
        self.labelPayment.setGeometry(QtCore.QRect(280, 270, 100, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelPayment.setFont(font)
        self.labelPayment.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelPayment.setObjectName("labelPayment")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(240, 140, 309, 100))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.lineSalary = QtWidgets.QLineEdit(self.widget)
        self.lineSalary.setObjectName("lineSalary")
        self.gridLayout.addWidget(self.lineSalary, 0, 1, 1, 1)
        self.labelDaysToWork = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelDaysToWork.setFont(font)
        self.labelDaysToWork.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelDaysToWork.setObjectName("labelDaysToWork")
        self.gridLayout.addWidget(self.labelDaysToWork, 1, 0, 1, 1)
        self.labelSalary = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelSalary.setFont(font)
        self.labelSalary.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelSalary.setObjectName("labelSalary")
        self.gridLayout.addWidget(self.labelSalary, 0, 0, 1, 1)
        self.labelJustifiedAbsences = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelJustifiedAbsences.setFont(font)
        self.labelJustifiedAbsences.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelJustifiedAbsences.setObjectName("labelJustifiedAbsences")
        self.gridLayout.addWidget(self.labelJustifiedAbsences, 3, 0, 1, 1)
        self.lineDaysToWork = QtWidgets.QLineEdit(self.widget)
        self.lineDaysToWork.setText("")
        self.lineDaysToWork.setObjectName("lineDaysToWork")
        self.gridLayout.addWidget(self.lineDaysToWork, 1, 1, 1, 1)
        self.labelWorkedDays = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelWorkedDays.setFont(font)
        self.labelWorkedDays.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelWorkedDays.setObjectName("labelWorkedDays")
        self.gridLayout.addWidget(self.labelWorkedDays, 2, 0, 1, 1)
        self.lineJustifiedAbsences = QtWidgets.QLineEdit(self.widget)
        self.lineJustifiedAbsences.setObjectName("lineJustifiedAbsences")
        self.gridLayout.addWidget(self.lineJustifiedAbsences, 3, 1, 1, 1)
        self.lineWorkedDays = QtWidgets.QLineEdit(self.widget)
        self.lineWorkedDays.setObjectName("lineWorkedDays")
        self.gridLayout.addWidget(self.lineWorkedDays, 2, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btnCalculateSalary.setText(_translate("MainWindow", "Calcular Salário"))
        self.labelPayment.setText(_translate("MainWindow", "Valor à ser Pago:"))
        self.labelDaysToWork.setText(_translate("MainWindow", "Dias Previsto Para Trabalhar:"))
        self.labelSalary.setText(_translate("MainWindow", "Salario:"))
        self.labelJustifiedAbsences.setText(_translate("MainWindow", "Faltas Justificadas:"))
        self.labelWorkedDays.setText(_translate("MainWindow", "Dias Trabalhados:"))
